#!/bin/bash
# ================================================================
# GPU Test — Wan2.2-Animate via ComfyUI (self-hosted)
# npm run test:worker-gpu
#
# Tests REAL inference. No mocks. No fal.ai.
# Produces a real mp4 generated by Wan2.2-Animate.
#
# Prerequisites:
#   1. MODEL_PATH set to ComfyUI models directory (~22GB)
#   2. Docker image built: docker build -t wan-animate-worker:local worker/
#   3. GPU available: nvidia-smi
#
# Usage:
#   MODEL_PATH=/path/to/models npm run test:worker-gpu
#
#   With local test files:
#   TEST_VIDEO=/path/video.mp4 TEST_IMAGE=/path/image.png \
#   MODEL_PATH=/path/to/models npm run test:worker-gpu
# ================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
WORKER_DIR="$PROJECT_ROOT/worker"
ENV_FILE="$PROJECT_ROOT/.env.local"
IMAGE="wan-animate-worker:local"
OUTPUT_DIR="${OUTPUT_DIR:-/tmp/wan-gpu-test}"
mkdir -p "$OUTPUT_DIR"

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; BLUE='\033[0;34m'; NC='\033[0m'
ok()     { echo -e "${GREEN}  ✓${NC} $*"; }
fail()   {
    echo ""
    echo -e "${RED}━━━ FAILED ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e "${RED}  ✗ $*${NC}"
    echo ""
    diagnose "$*"
    echo -e "${RED}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    exit 1
}
warn()   { echo -e "${YELLOW}  ⚠${NC} $*"; }
info()   { echo -e "${BLUE}  →${NC} $*"; }
phase()  { echo ""; echo "━━━ $* ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"; echo ""; }

# ── Load .env.local ──────────────────────────────────────────────
if [ -f "$ENV_FILE" ]; then
    while IFS='=' read -r k v; do
        [[ "$k" =~ ^[[:space:]]*# ]] && continue; [[ -z "$k" ]] && continue
        k="${k// /}"; v="${v// /}"
        [ -z "${!k+x}" ] && export "$k=$v" 2>/dev/null || true
    done < "$ENV_FILE"
fi

MODEL_PATH="${MODEL_PATH:-${WAN_MODEL_PATH:-}}"
TEST_QUALITY="${TEST_QUALITY:-fast}"
# Public short test video — 4s, single person talking to camera
TEST_VIDEO_URL="${TEST_VIDEO_URL:-https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4}"
# Public portrait image — clear front-facing face
TEST_IMAGE_URL="${TEST_IMAGE_URL:-https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=512&h=512&fit=crop&crop=face}"

# ── Error diagnosis ──────────────────────────────────────────────
diagnose() {
    local msg="${1:-}"
    echo "  Diagnosis:"
    if echo "$msg $LAST_LOG" | grep -qi "model.*not found\|No file matching\|diffusion.*missing"; then
        echo "    → Wan2.2-Animate model weights missing."
        echo "      Run: bash worker/scripts/download-models.sh $MODEL_PATH"
        echo "      Then verify: npm run test:models"
    elif echo "$msg $LAST_LOG" | grep -qi "out of memory\|CUDA.*memory\|VRAM\|cudaMalloc"; then
        echo "    → CUDA out of memory."
        echo "      Wan2.2-Animate-14B needs ≥16GB VRAM."
        echo "      Use TEST_QUALITY=fast to reduce memory."
        echo "      Or upgrade to RTX 4090 (24GB)."
    elif echo "$msg $LAST_LOG" | grep -qi "node.*not found\|class_type.*invalid\|node_errors\|ImportError\|ModuleNotFoundError"; then
        echo "    → ComfyUI custom node missing or failed to import."
        echo "      Rebuild image: docker build -t $IMAGE $WORKER_DIR"
        echo "      Check build logs for pip install errors."
    elif echo "$msg $LAST_LOG" | grep -qi "ComfyUI.*died\|process died\|ComfyUI.*crash"; then
        echo "    → ComfyUI crashed during startup."
        echo "      Check LAST_LOG above for Python errors."
        echo "      Common cause: CUDA/PyTorch version mismatch."
    elif echo "$msg $LAST_LOG" | grep -qi "ffmpeg\|ffprobe"; then
        echo "    → ffmpeg/ffprobe not found in container."
        echo "      Rebuild image (ffmpeg is installed in Dockerfile)."
    elif echo "$msg $LAST_LOG" | grep -qi "workflow\|prompt_id\|node_error\|PATCH:"; then
        echo "    → Workflow JSON invalid or unpatched."
        echo "      Check worker/workflows/wan22_animate_replace_api.json"
        echo "      All PATCH: values must be replaced by handler.py"
    elif echo "$msg $LAST_LOG" | grep -qi "output.*not found\|no.*mp4\|gifs.*empty\|Duration.*0"; then
        echo "    → Inference ran but produced no output."
        echo "      Check ComfyUI logs above for sampler errors."
        echo "      Possible: wrong video dimensions (must be multiples of 16)."
    elif echo "$msg $LAST_LOG" | grep -qi "Connection refused\|Cannot reach ComfyUI"; then
        echo "    → ComfyUI not ready when handler started."
        echo "      Increase sleep time in test or start.sh wait loop."
    elif echo "$msg $LAST_LOG" | grep -qi "No GPU_TEST_RESULT"; then
        echo "    → Container exited without producing result."
        echo "      Most likely: ComfyUI crashed. Check full log above."
    else
        echo "    → Check the full container log above for the root cause."
    fi
}

LAST_LOG=""

# ================================================================
echo ""
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║  Wan2.2-Animate GPU Test — ComfyUI self-hosted              ║"
echo "║  Quality: $TEST_QUALITY                                         ║"
echo "╚══════════════════════════════════════════════════════════════╝"

# ── Phase 1: Prerequisites ───────────────────────────────────────
phase "Phase 1 — Prerequisites"

command -v docker &>/dev/null || fail "Docker not installed"
docker info &>/dev/null       || fail "Docker daemon not running"
ok "Docker: $(docker --version | awk '{print $3}' | tr -d ',')"

command -v nvidia-smi &>/dev/null || fail "nvidia-smi not found — GPU required"
GPU_INFO=$(nvidia-smi --query-gpu=name,memory.total --format=csv,noheader 2>/dev/null | head -1)
ok "GPU: $GPU_INFO"

VRAM_MB=$(nvidia-smi --query-gpu=memory.total --format=csv,noheader,nounits 2>/dev/null | head -1 | tr -d ' ')
if [ "${VRAM_MB:-0}" -lt 14000 ]; then
    warn "GPU has ${VRAM_MB}MB VRAM — Wan2.2-Animate-14B needs ≥16GB (prefer 24GB)"
fi

# ── Phase 2: Model path ──────────────────────────────────────────
phase "Phase 2 — Model weights"

[ -n "$MODEL_PATH" ] || fail \
    "MODEL_PATH not set.\n\n  Set in .env.local:  MODEL_PATH=/path/to/models\n  Or: MODEL_PATH=/path/to/models npm run test:worker-gpu\n  Download: bash worker/scripts/download-models.sh /path/to/models"
[ -d "$MODEL_PATH" ] || fail "MODEL_PATH does not exist: $MODEL_PATH"
ok "Model path: $MODEL_PATH"

# Run test:models check inline
info "Checking model files..."
bash "$SCRIPT_DIR/test-models.sh" 2>&1 | grep -E "✓|✗|⚠" | head -20
# If test-models exits non-zero, we fail here
bash "$SCRIPT_DIR/test-models.sh" > /dev/null 2>&1 || \
    fail "Model check failed. Run: npm run test:models for details."
ok "All required models present"

# ── Phase 3: Docker image ────────────────────────────────────────
phase "Phase 3 — Docker image"

if ! docker image inspect "$IMAGE" &>/dev/null; then
    info "Image not found — building (5-10 min)..."
    docker build -t "$IMAGE" "$WORKER_DIR" || fail "Docker build failed"
fi
ok "Image: $IMAGE"

# ── Phase 4: ComfyUI node verification ──────────────────────────
phase "Phase 4 — ComfyUI node verification"
info "Starting ComfyUI briefly to check all required nodes..."

NODE_LOG=$(docker run --rm \
    --name "wan-node-check-$$" \
    --gpus all \
    -v "$MODEL_PATH:/comfyui/models:ro" \
    -e LOCAL_TEST=true \
    -e COMFYUI_HOST=http://127.0.0.1:8188 \
    "$IMAGE" \
    bash -c '
set -e
# Start ComfyUI
python3 /comfyui/main.py \
    --listen 127.0.0.1 --port 8188 \
    --disable-auto-launch --preview-method none \
    --log-stdout &
CPID=$!

# Wait up to 90s for ComfyUI
for i in $(seq 1 30); do
    sleep 3
    if curl -sf --max-time 3 http://127.0.0.1:8188/system_stats >/dev/null 2>&1; then
        echo "NODE_CHECK:comfyui_ready"
        break
    fi
    kill -0 $CPID 2>/dev/null || { echo "NODE_CHECK:comfyui_died"; exit 1; }
done

# Fetch node list
if ! curl -sf --max-time 10 http://127.0.0.1:8188/object_info > /tmp/nodes.json 2>/dev/null; then
    echo "NODE_CHECK:fetch_failed"
    kill $CPID 2>/dev/null; exit 1
fi

# Check required nodes
python3 << PYCHECK
import json
with open("/tmp/nodes.json") as f:
    nodes = json.load(f)

required = [
    "WanVideoModelLoader",
    "WanVideoVAELoader",
    "WanVideoTextEncodeCached",
    "WanVideoClipVisionEncode",
    "WanVideoAnimateEmbeds",
    "WanVideoSampler",
    "WanVideoDecode",
    "OnnxDetectionModelLoader",
    "OnnxPoseModelLoader",
    "PoseAndFaceDetection",
    "VHS_LoadVideo",
    "VHS_VideoCombine",
    "SAM2ModelLoader",
    "Sam2Segmentation",
    "CLIPVisionLoader",
]

ok, missing = [], []
for n in required:
    (ok if n in nodes else missing).append(n)

for n in ok:
    print(f"NODE_CHECK:ok:{n}")
for n in missing:
    print(f"NODE_CHECK:missing:{n}")
print(f"NODE_CHECK:total:{len(nodes)}")
PYCHECK

kill $CPID 2>/dev/null; wait $CPID 2>/dev/null || true
' 2>&1 || true)

LAST_LOG="$NODE_LOG"

if echo "$NODE_LOG" | grep -q "NODE_CHECK:comfyui_died"; then
    fail "ComfyUI crashed during startup"
fi
if ! echo "$NODE_LOG" | grep -q "NODE_CHECK:comfyui_ready"; then
    fail "ComfyUI did not become ready within 90s"
fi

MISSING_NODES=$(echo "$NODE_LOG" | grep "NODE_CHECK:missing:" | sed 's/NODE_CHECK:missing://' | tr '\n' ' ')
if [ -n "$MISSING_NODES" ]; then
    fail "Missing ComfyUI nodes: $MISSING_NODES\nRebuild image: docker build -t $IMAGE $WORKER_DIR"
fi

OK_NODES=$(echo "$NODE_LOG" | grep "NODE_CHECK:ok:" | wc -l | tr -d ' ')
TOTAL_NODES=$(echo "$NODE_LOG" | grep "NODE_CHECK:total:" | sed 's/NODE_CHECK:total://')
ok "All required nodes loaded ($OK_NODES/15 checked, $TOTAL_NODES total)"

# ── Phase 5: Real GPU inference ──────────────────────────────────
phase "Phase 5 — Real GPU inference"

info "Quality:    $TEST_QUALITY"
info "Video URL:  $TEST_VIDEO_URL"
info "Image URL:  $TEST_IMAGE_URL"
info "Output dir: $OUTPUT_DIR"
echo ""
info "Starting inference — this takes 2-10 minutes on RTX 4090 (quality=fast ~3min)"
info "LOCAL_TEST=true: output saved to $OUTPUT_DIR"
echo ""

JOB_ID="gpu-test-$(date +%s)"
PAYLOAD="{\"id\":\"$JOB_ID\",\"input\":{\"user_video_url\":\"$TEST_VIDEO_URL\",\"character_image_url\":\"$TEST_IMAGE_URL\",\"quality\":\"$TEST_QUALITY\",\"mode\":\"replacement\",\"keep_original_audio\":true}}"

INFERENCE_LOG=$(docker run --rm \
    --name "wan-inference-$$" \
    --gpus all \
    -e LOCAL_TEST=true \
    -e COMFYUI_HOST=http://127.0.0.1:8188 \
    -e WAN_WORKFLOW_PATH=/app/workflows/wan22_animate_replace_api.json \
    -e COMFYUI_OUTPUT_DIR=/comfyui/output \
    -e COMFYUI_MODELS=/comfyui/models \
    -e TEST_PAYLOAD="$PAYLOAD" \
    -v "$MODEL_PATH:/comfyui/models:ro" \
    -v "$OUTPUT_DIR:/tmp/gpu-output" \
    "$IMAGE" \
    bash -c '
set -e
# Start ComfyUI (suppress verbose logs, show only errors)
python3 /comfyui/main.py \
    --listen 127.0.0.1 --port 8188 \
    --disable-auto-launch --preview-method none \
    --log-stdout 2>&1 | grep -E "ERROR|WARN|Loaded|Custom" &
CPID=$!

# Wait for ComfyUI
echo "[GPU-TEST] Waiting for ComfyUI..."
for i in $(seq 1 60); do
    sleep 5
    if curl -sf http://127.0.0.1:8188/system_stats >/dev/null 2>&1; then
        echo "[GPU-TEST] ComfyUI ready after $((i*5))s"
        break
    fi
    kill -0 $CPID 2>/dev/null || { echo "[GPU-TEST] ComfyUI died"; exit 1; }
    echo "[GPU-TEST] Still waiting ($((i*5))s)..."
done

# Patch output dir in handler to map to mounted volume
export COMFYUI_OUTPUT_DIR=/comfyui/output

# Run handler
python3 -c "
import json, os, sys, types, runpod
runpod.serverless = types.SimpleNamespace(start=lambda cfg: None)
sys.path.insert(0, \"/app\")
import handler

payload = json.loads(os.environ[\"TEST_PAYLOAD\"])
print(\"[GPU-TEST] Job:\", payload[\"id\"])
print(\"[GPU-TEST] Mode:\", payload[\"input\"][\"mode\"], \"| Quality:\", payload[\"input\"][\"quality\"])

result = handler.handler(payload)
print(\"GPU_TEST_RESULT:\" + json.dumps(result))
"

kill $CPID 2>/dev/null; wait $CPID 2>/dev/null || true
' 2>&1)

LAST_LOG="$INFERENCE_LOG"

# Show important lines from the log
echo "$INFERENCE_LOG" | grep -E "GPU-TEST|handler|ERROR|WARN|Loaded|output_video|execution_time" | \
    while IFS= read -r line; do echo "  $line"; done

# Extract result
RESULT_JSON=$(echo "$INFERENCE_LOG" | grep "^GPU_TEST_RESULT:" | sed 's/^GPU_TEST_RESULT://' | tail -1)
[ -n "$RESULT_JSON" ] || fail "No GPU_TEST_RESULT in output — container may have crashed"

WORKER_ERROR=$(echo "$RESULT_JSON" | python3 -c "import json,sys; d=json.load(sys.stdin); print(d.get('error',''))" 2>/dev/null || echo "")
[ -z "$WORKER_ERROR" ] || fail "Worker error: $WORKER_ERROR"

VIDEO_URL=$(echo "$RESULT_JSON" | python3 -c "import json,sys; d=json.load(sys.stdin); print(d.get('output_video_url',''))" 2>/dev/null || echo "")
[ -n "$VIDEO_URL" ] || fail "No output_video_url in result: $RESULT_JSON"

EXEC_MS=$(echo "$RESULT_JSON" | python3 -c "import json,sys; d=json.load(sys.stdin); print(d.get('execution_time_ms',0))" 2>/dev/null || echo "0")
ok "Generation complete in $((EXEC_MS / 1000))s"

# Locate the output file
OUTPUT_FILE=""
if [[ "$VIDEO_URL" == file://* ]]; then
    CONTAINER_PATH="${VIDEO_URL#file://}"
    # Container's /tmp is mounted to $OUTPUT_DIR/gpu-output in our host
    HOST_FILE="$OUTPUT_DIR/$(basename "$CONTAINER_PATH")"
    if [ -f "$HOST_FILE" ]; then
        OUTPUT_FILE="$HOST_FILE"
    else
        # Try finding any new mp4 in output dir
        OUTPUT_FILE=$(find "$OUTPUT_DIR" -name "*.mp4" -newer /tmp -maxdepth 2 2>/dev/null | head -1 || true)
    fi
fi

# ── Phase 6: Validate output with ffprobe ────────────────────────
phase "Phase 6 — Video validation"

if [ -z "$OUTPUT_FILE" ] || [ ! -f "$OUTPUT_FILE" ]; then
    warn "Output file not found on host at $OUTPUT_DIR"
    warn "Container path was: $VIDEO_URL"
    warn "Listing $OUTPUT_DIR:"
    ls -la "$OUTPUT_DIR" 2>/dev/null || true
    fail "Cannot validate — output file not accessible on host"
fi

ok "Output file: $OUTPUT_FILE"
SIZE=$(stat -f%z "$OUTPUT_FILE" 2>/dev/null || stat -c%s "$OUTPUT_FILE" 2>/dev/null || echo 0)
[ "$SIZE" -gt 10000 ] || fail "Output file too small (${SIZE} bytes) — likely empty"
ok "File size: $SIZE bytes ($(numfmt --to=iec "$SIZE" 2>/dev/null || echo "${SIZE}B"))"

if ! command -v ffprobe &>/dev/null; then
    warn "ffprobe not on host — running validation inside Docker"
    FFPROBE_OUT=$(docker run --rm \
        -v "$OUTPUT_FILE:/validate.mp4:ro" \
        "$IMAGE" \
        ffprobe -v quiet -print_format json -show_streams -show_format /validate.mp4 2>&1 || echo "{}")
else
    FFPROBE_OUT=$(ffprobe -v quiet -print_format json -show_streams -show_format "$OUTPUT_FILE" 2>&1 || echo "{}")
fi

DURATION=$(echo "$FFPROBE_OUT" | python3 -c "import json,sys; d=json.load(sys.stdin); print(d.get('format',{}).get('duration','0'))" 2>/dev/null || echo "0")
CODEC=$(echo "$FFPROBE_OUT" | python3 -c "import json,sys; d=json.load(sys.stdin); v=[s for s in d.get('streams',[]) if s.get('codec_type')=='video']; print(v[0].get('codec_name','?') if v else '?')" 2>/dev/null || echo "?")
WIDTH=$(echo "$FFPROBE_OUT" | python3 -c "import json,sys; d=json.load(sys.stdin); v=[s for s in d.get('streams',[]) if s.get('codec_type')=='video']; print(v[0].get('width','?') if v else '?')" 2>/dev/null || echo "?")
HEIGHT=$(echo "$FFPROBE_OUT" | python3 -c "import json,sys; d=json.load(sys.stdin); v=[s for s in d.get('streams',[]) if s.get('codec_type')=='video']; print(v[0].get('height','?') if v else '?')" 2>/dev/null || echo "?")
HAS_AUDIO=$(echo "$FFPROBE_OUT" | python3 -c "import json,sys; d=json.load(sys.stdin); a=[s for s in d.get('streams',[]) if s.get('codec_type')=='audio']; print('yes' if a else 'no')" 2>/dev/null || echo "?")

echo ""
echo "  ┌─────────────────────────────────────────────────────────"
echo "  │  ffprobe results"
printf "  │  %-12s %s\n" "Duration:"    "${DURATION}s"
printf "  │  %-12s %s\n" "Resolution:"  "${WIDTH}x${HEIGHT}"
printf "  │  %-12s %s\n" "Codec:"       "${CODEC}"
printf "  │  %-12s %s\n" "Audio:"       "${HAS_AUDIO}"
echo "  └─────────────────────────────────────────────────────────"
echo ""

python3 -c "import sys; sys.exit(0 if float('${DURATION}' if '${DURATION}' not in ('?','') else '0') > 0 else 1)" 2>/dev/null \
    && ok "Duration > 0" \
    || fail "Duration is 0 — inference completed but video is empty. Check ComfyUI logs."

[ "$CODEC" != "?" ] && ok "Video codec: $CODEC" || warn "Could not detect video codec"
[ "$WIDTH" != "?" ] && [ "$WIDTH" != "0" ] && ok "Resolution: ${WIDTH}x${HEIGHT}" || warn "Could not detect resolution"

# ── Success ──────────────────────────────────────────────────────
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo -e "${GREEN}  ✅ GPU TEST PASSED${NC}"
echo ""
echo "  Output mp4:   $OUTPUT_FILE"
echo "  Duration:     ${DURATION}s"
echo "  Resolution:   ${WIDTH}x${HEIGHT}"
echo "  Codec:        ${CODEC}"
echo "  Generation:   $((EXEC_MS / 1000))s total"
echo ""
echo "  The worker is generating real Wan2.2-Animate video."
echo "  Next step: deploy to RunPod Serverless."
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
